[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gawe-video"
version = "0.1.0"
description = "CLI tool to generate tutorial videos from Markdown files"
readme = "README.md"
authors = [{name = "mhfirdaus"}]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
  "moviepy>=1.0.3",
  "edge-tts>=6.1.12",
  "Pygments>=2.17.0",
  "Pillow>=10.2.0",
  "markdown-it-py>=3.0.0",
  "rich>=13.7.0",
  "typer>=0.12.3",
  "streamlit>=1.32.0",
  "watchdog>=4.0.0"
]

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]

[project.scripts]
gawe-video = "gawe_video.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
